/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jfrem;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JOptionPane;
import ko.Empleado;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1CFont;





/**
 *
 * @author angel
 */
public class FrmEmpleados extends javax.swing.JFrame {
    
    
      public FrmEmpleados() {
        initComponents();
        // se coloca titulo en la parte superior de la pantalla
        this.setTitle("Ko'áame");
        // centrar
        this.setLocationRelativeTo(jfrem.FrmEmpleados.this);
        // expandir
        //this.setExtendedState(Basicos.MAXIMIZED_BOTH);
         Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("MisImgs/Logok.png"));
         this.setIconImage(icono);
      
    
  
    }

    static final int CANTIDAD_MAXIMA_EMPLEADO = 10;
    int contador = 0;
    Empleado vecEmpleado[] = 
    new Empleado [CANTIDAD_MAXIMA_EMPLEADO];
    Empleado emp = null;
    
    
    
    /**
     * Creates new form FrmEmpleados
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLimpiarEmp = new javax.swing.JButton();
        btnGuardarEmp = new javax.swing.JButton();
        btnBuascarEmp = new javax.swing.JButton();
        btnRegresarEmp = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtIdEmp = new javax.swing.JTextField();
        txtNumCarnetEmp = new javax.swing.JTextField();
        txtNombreEmp = new javax.swing.JTextField();
        txtApellidoEmp = new javax.swing.JTextField();
        txtPesoEmp = new javax.swing.JTextField();
        txtEstaturaEmp = new javax.swing.JTextField();
        cboTipoDocEmp = new javax.swing.JComboBox<>();
        dcNacimientoEmp = new com.toedter.calendar.JDateChooser();
        cboGeneroEmp = new javax.swing.JComboBox<>();
        cboTipoSangreEmp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MisImgs/LogoK160.png"))); // NOI18N

        btnLimpiarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/nuevo.png"))); // NOI18N
        btnLimpiarEmp.setText("NUEVO");
        btnLimpiarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEmpActionPerformed(evt);
            }
        });

        btnGuardarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/GuardarTodo.png"))); // NOI18N
        btnGuardarEmp.setText("GUARDAR");
        btnGuardarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpActionPerformed(evt);
            }
        });

        btnBuascarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/lupa.png"))); // NOI18N
        btnBuascarEmp.setText("BUSCAR");
        btnBuascarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuascarEmpActionPerformed(evt);
            }
        });

        btnRegresarEmp.setText("REGRESAR");
        btnRegresarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarEmpActionPerformed(evt);
            }
        });

        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/pdf.png"))); // NOI18N
        btnPDF.setText("PDF");
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegresarEmp)
                            .addComponent(btnBuascarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(btnLimpiarEmp)
                .addGap(39, 39, 39)
                .addComponent(btnGuardarEmp)
                .addGap(43, 43, 43)
                .addComponent(btnBuascarEmp)
                .addGap(34, 34, 34)
                .addComponent(btnPDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(btnRegresarEmp)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 640));

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 790, 140));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setText("NUMERO DOCUMENTO");

        jLabel3.setText("TIPO DOCUMENTO");

        jLabel4.setText("NUMERO CARNET");

        jLabel5.setText("FECHA DE NACIMIENTO");

        jLabel6.setText("NOMBRE");

        jLabel7.setText("APELLIDOS");

        jLabel8.setText("GENERO");

        jLabel9.setText("TIPO DE SANGRE");

        jLabel10.setText("PESO (Kg)");

        jLabel11.setText("ESTATURA (m)");

        txtPesoEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoEmpActionPerformed(evt);
            }
        });

        cboTipoDocEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COCINERO", "REPARTIDOR", "MECERO", " " }));
        cboTipoDocEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoDocEmpActionPerformed(evt);
            }
        });

        cboGeneroEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FEMENINO", "MASCULINO" }));

        cboTipoSangreEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboGeneroEmp, 0, 264, Short.MAX_VALUE)
                    .addComponent(txtNumCarnetEmp)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtIdEmp)
                    .addComponent(txtNombreEmp)
                    .addComponent(txtPesoEmp))
                .addGap(170, 170, 170)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidoEmp)
                    .addComponent(txtEstaturaEmp)
                    .addComponent(cboTipoDocEmp, 0, 280, Short.MAX_VALUE)
                    .addComponent(dcNacimientoEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboTipoSangreEmp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoDocEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumCarnetEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dcNacimientoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboGeneroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoSangreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstaturaEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 790, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEmpActionPerformed
        // TODO add your handling code here:
        txtApellidoEmp.setText("");
        txtNombreEmp.setText("");
        txtEstaturaEmp.setText("");
        dcNacimientoEmp.setDate(null);
        txtIdEmp.setText("");
        txtNumCarnetEmp.setText("");
        txtEstaturaEmp.setText("");
        txtPesoEmp.setText("");
        
        cboTipoDocEmp.setSelectedIndex(-1);
        cboTipoSangreEmp.setSelectedIndex(-1);
        cboGeneroEmp.setSelectedIndex(-1);
        
        txtIdEmp.grabFocus();
    }//GEN-LAST:event_btnLimpiarEmpActionPerformed

    private void btnGuardarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpActionPerformed
        // TODO add your handling code here:
        if (contador < vecEmpleado.length) {
            
            int ID = Integer.parseInt(txtIdEmp.getText());
            int TIPODOCUMENTO = cboTipoDocEmp.getSelectedIndex();
            int CARNET = Integer.parseInt(txtNumCarnetEmp.getText());
            String NOMBRE = txtNombreEmp.getText();
            String APELLIDOS = txtApellidoEmp.getText();
            Date FECHANACIMIENTO = dcNacimientoEmp.getDate();
            String TIPOSANGRE = cboTipoSangreEmp.getSelectedItem().toString();
            char GENERO = cboGeneroEmp.getSelectedItem().toString().charAt(0);
            double PESO = Double.parseDouble(txtPesoEmp.getText());
            double ESTATURA = Double.parseDouble( txtEstaturaEmp.getText());
             
             
            emp = new Empleado(ID, TIPODOCUMENTO, CARNET, NOMBRE, APELLIDOS, FECHANACIMIENTO, TIPOSANGRE, GENERO, PESO, ESTATURA);
            vecEmpleado[contador] = emp;
            contador ++;
            
            JOptionPane.showMessageDialog(this,"Se ingreso un nuevo empleado");
            
        }else{
          JOptionPane.showMessageDialog(this,"No hay mas lugares para empleados");  
             
            
        }
 
        
    }//GEN-LAST:event_btnGuardarEmpActionPerformed

    private void txtPesoEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoEmpActionPerformed

    private void btnBuascarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuascarEmpActionPerformed
        // TODO add your handling code here:
        
        String strID = txtIdEmp.getText();
        if(strID.length() == 0){
        strID = (String)JOptionPane.showInputDialog(
                "Debe digitar el numero de identificacion");  
            if (strID == null) 
                return;
        }
        
        int k = 0;
        boolean sw = false;
       int ID = Integer.parseInt(strID); 
       while (k < contador && sw == false) {
       
           emp = vecEmpleado[k];
           if(emp.getID() == ID){
           sw = true;
           }else{
               k++;
           }
       
       }
        
       if(sw == true){
       
       
           txtIdEmp.setText(emp.getID() + "");
           txtNumCarnetEmp.setText(emp.getNumeroCarnet() + "");
           txtNombreEmp.setText(emp.getNombre());
           txtApellidoEmp.setText(emp.getApellido());
            dcNacimientoEmp.setDate(emp.getNacimiento());
            
            cboTipoSangreEmp.setSelectedItem(emp.getTipoSangre() + "");
            cboTipoDocEmp.setSelectedIndex(emp.getTipoID());
            int INDICEGENERO = (emp.getGenero() == 'F' ? 0 : 1);
            cboGeneroEmp.setSelectedIndex( INDICEGENERO );
            txtPesoEmp.setText(emp.getPeso()+ "");
            txtEstaturaEmp.setText(emp.getEstatura() + "");
       }else{
           
            
             JOptionPane.showMessageDialog(this,"No se econtro al empleado");  
           
           
       
       
       } 
       
       
       
        
        
        
    }//GEN-LAST:event_btnBuascarEmpActionPerformed

    private void btnRegresarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarEmpActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_btnRegresarEmpActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed


try{
    PDDocument documento = new PDDocument();
    PDPage pagina = new PDPage(PDRectangle.A6);
    documento.addPage(pagina);
    PDPageContentStream contenido = new PDPageContentStream(documento,pagina);
    
    contenido.beginText();
    //contenido.setFont(PDTypelFont.TIMES_BOLD,12);
    contenido.newLineAtOffset(20, pagina.getMediaBox().getHeight()-54);
    
    contenido.showText( this.txtNombreEmp.getText().toString());
    
    contenido.endText();
    
    contenido.showText( this.txtApellidoEmp.getText().toString());
    
    contenido.endText();
    
    contenido.showText( this.txtIdEmp.getText().toString());
    
    contenido.endText();
    
    contenido.showText( this.txtNumCarnetEmp.getText().toString());
    
    contenido.endText();
    
    contenido.showText( this.txtEstaturaEmp.getText().toString());
    
    contenido.endText();
    
    contenido.showText( this.dcNacimientoEmp.getDate().toString());
    
    contenido.endText();
    
    contenido.showText( this.cboTipoSangreEmp.getSelectedItem().toString());
    
    contenido.endText();
    
    contenido.showText( this.cboTipoSangreEmp.getSelectedItem().toString());
    
    contenido.endText();
    
    contenido.showText( this.cboTipoDocEmp.getSelectedItem().toString());
    
    contenido.endText();    
    
    contenido.close();
    
    documento.save("C:\\Users\\angel\\Documents\\NetBeansProjects\\KO Solicitud.pdf");


}
catch(Exception x){


    System.out.println("ERROR "+x.getMessage().toString());

}




        // TODO add your handling code here:
    }//GEN-LAST:event_btnPDFActionPerformed

    private void cboTipoDocEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoDocEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoDocEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuascarEmp;
    private javax.swing.JButton btnGuardarEmp;
    private javax.swing.JButton btnLimpiarEmp;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnRegresarEmp;
    private javax.swing.JComboBox<String> cboGeneroEmp;
    private javax.swing.JComboBox<String> cboTipoDocEmp;
    private javax.swing.JComboBox<String> cboTipoSangreEmp;
    private com.toedter.calendar.JDateChooser dcNacimientoEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtApellidoEmp;
    private javax.swing.JTextField txtEstaturaEmp;
    private javax.swing.JTextField txtIdEmp;
    private javax.swing.JTextField txtNombreEmp;
    private javax.swing.JTextField txtNumCarnetEmp;
    private javax.swing.JTextField txtPesoEmp;
    // End of variables declaration//GEN-END:variables
}
